version: "3"
services:
  shop-graphql-api:
    container_name: shop-graphql-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    expose:
      - 3333 
    ports:
      - 3333:3333
    depends_on:
      - postgres
    env_file:
      - .env
    command: bash -c "npx prisma migrate deploy && npm run start:dev"

  postgres:
    image: postgres
    container_name: postgres-graphql
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql_graphql/data/  # persist data even if container shuts down
volumes:
  database-data: